### PR TITLE
Support simple resource class selection

### PR DESCRIPTION
**Pull request by negz**
https://github.com/crossplaneio/crossplane/pull/926
https://github.com/crossplaneio/crossplane/pull/927
https://github.com/crossplaneio/crossplane-runtime/pull/48

Updates angryjet to reflect the above changes.

### Checklist

I have:
- [x] Run `make reviewable` to ensure this PR is ready for review.
- [x] Ensured this PR contains a neat, self documenting set of commits.

### CODE REVIEW

**Comment by negz** [comment]
> How would you feel about incorporating #2 into this PR? 

I agree with the sentiment, but I'm inclined to tackle it in a separate PR because it's a slightly less trivial change than it might seem. angryjet doesn't know how to write anything but methods at the moment, so we'd probably have to teach `generate.WriteMethods` how to know whether the methods it was writing should satisfy an interface.

**Comment by soorena776** [comment]
@negz  FYI, my changes also have a change in the api (adding `GetCondition`), so you might want to wait until that is checked in, if you don't want to open another pr later

**Comment by negz** [comment]
@soorena776 Thanks for the heads up. My suspicion is it might be best to add your changes in a separate PR, because it might take me a while to merge this one.

**Comment by hasheddan** [comment]
> I agree with the sentiment, but I'm inclined to tackle it in a separate PR because it's a slightly less trivial change than it might seem.

@negz sounds good!

**Pull request merged**
